_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
            "3":
                - 16
                - 23
                - 55
                - 61
            "4": 3.12.6
            "5": 0.19.11
            "6": 4.44.2
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 8
dataset_size:
    value: 31047
learning_rate:
    value: 0.0001
model_channels:
    value: 256
num_epochs:
    value: 1000
num_frames:
    value: 100
num_timesteps:
    value: 1000
pose_dim:
    value: 120
