augmentation_noise_std: 0.01
augmentation_speed_factors:
- 0.8
- 1.2
batch_size: 1
bert_model: bert-base-multilingual-cased
default_max_frames: 256
device: auto
dropout: 0.1
ff_multiplier: 4
gloss_vocab_size: 10000
hidden_dim: 1024
learning_rate: 0.0001
loss_alpha: 1.0
loss_beta: 0.5
loss_gamma: 0.3
max_frames: 500
max_sequence_length: 512
min_frames: 30
mixed_precision: true
model_size: large
num_epochs: 50
num_heads: 16
num_languages: 8
num_layers: 12
num_priorities: 8
num_workers: 2
patience: 10
pin_memory: true
pose_dim: 150
use_data_augmentation: true
weight_decay: 0.01
