augmentation_noise_std: 0.01
augmentation_speed_factors:
- 0.8
- 1.2
batch_size: 4
bert_model: bert-base-multilingual-cased
default_max_frames: 256
device: auto
dropout: 0.1
ff_multiplier: 2
gloss_vocab_size: 2000
hidden_dim: 512
learning_rate: 5.0e-05
loss_alpha: 1.0
loss_beta: 0.5
loss_gamma: 0.3
max_frames: 500
max_sequence_length: 512
min_frames: 30
mixed_precision: true
model_size: small
num_epochs: 100
num_heads: 8
num_languages: 8
num_layers: 4
num_priorities: 8
num_workers: 2
patience: 10
pin_memory: true
pose_dim: 150
use_data_augmentation: true
weight_decay: 0.01
